/* $$43564A43$$ WARNING: Do not edit. $$ This file has been instrumented by qualityscroll_cover_jacov 4.0.4-SNAPSHOT (Instrument Date:20240229123822) $$ */// RecentFileMenu.java

package net.sf.gogui.gui;

import java.io.File;
import java.util.ArrayList;

/** Menu for recent files.
    Automatically assigns short, but unique labels. */
public class RecentFileMenu
{
    public static transient boolean[] $qualityscroll_cover_coverage_buffer = $qualityscroll_cover_coverage_buffer_init();public static boolean[] $qualityscroll_cover_coverage_buffer_init() {try{if($qualityscroll_cover_coverage_buffer != null){return $qualityscroll_cover_coverage_buffer;}java.lang.Class<?> thisClass = RecentFileMenu.class.getClassLoader().loadClass("com.qualityscroll.cover.runtime.ProbeStore");java.lang.reflect.Method getProbesMethod = thisClass.getMethod("getProbes", long.class, long.class, long.class, java.lang.String.class, int.class);$qualityscroll_cover_coverage_buffer = (boolean[]) getProbesMethod.invoke(null,/* key(tuId + timestamp) */ -5684115456577363030L,/* translation unit id   */ -6798948191031104821L,/* timestamp             */ 1709177902693L,/* source file name      */ "RecentFileMenu.java",/* probe size            */ 44);}catch(java.lang.Exception e){throw new java.lang.RuntimeException(e);}return $qualityscroll_cover_coverage_buffer;}private static boolean $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(int index) {$qualityscroll_cover_coverage_buffer[index] = true;return true;}/** Callback for events generated by RecentFileMenu. */
    public interface Listener
    {
        void fileSelected(String label, File file);
    }

    public RecentFileMenu(String label, String path, Listener listener)
    {$qualityscroll_cover_coverage_buffer_init();
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(0);assert listener != null;
        m_listener = listener;
        RecentMenu.Listener recentListener = new RecentMenu.Listener()
        {
            @Override
			public void itemSelected(String label, String value)
            {
                $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(1);m_listener.fileSelected(label, new File(value));
            }
        };
        m_menu = new RecentMenu(label, path, recentListener);
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(2);for (int i = 0; (i < m_menu.getCount()) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(4) && false); ++i)
            {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(3);if ((! getFile(i).exists()) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(6) && false))
                {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(5);m_menu.remove(i);}}
    }

    public void add(File file)
    {
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(7);String name = file.getName();
        m_menu.add(name, file.toString());
        m_sameName.clear();
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(8);for (int i = 0; (i < getCount()) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(10) && false); ++i)
            {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(9);if ((getName(i).equals(name)) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(37) && false))
                {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(36);m_sameName.add(getValue(i));}}
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(11);if ((m_sameName.size() > 1) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(13) && false))
        {
            $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(12);int n = 0;
            $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(14);while (true)
            {
                $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(15);boolean samePrefix = true;
                $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(22);if ((file.toString().length() <= n) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(24) && false))
                    {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(23);break;}
                $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(25);char c = file.toString().charAt(n);
                $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(26);for (int i = 0; (i < m_sameName.size()) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(28) && false); ++i)
                {
                    $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(27);String sameName = m_sameName.get(i);
                    $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(33);if ((sameName.length() <= n || sameName.charAt(n) != c) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(35) && false))
                    {
                        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(34);samePrefix = false;
                        break;
                    }
                }
                $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(29);if ((! samePrefix) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(31) && false))
                    {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(30);break;}
                $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(32);++n;
            }
            $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(17);for (int i = 0; (i < getCount()) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(19) && false); ++i)
                {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(18);if ((getName(i).equals(name)) ? true : (!$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(21) && false))
                    {$qualityscroll_cover_jacov_probe_a1a548a4834e6acb(20);m_menu.setLabel(i, getValue(i).substring(n));}}
        }
    }

    /** Don't modify the items in this menu! */
    public GuiMenu getMenu()
    {
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(38);return m_menu.getMenu();
    }

    /** Set menu enabled if not empty, disabled otherwise. */
    public void updateEnabled()
    {
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(39);m_menu.updateEnabled();
    }

    private final Listener m_listener;

    private final RecentMenu m_menu;

    private final ArrayList<String> m_sameName = new ArrayList<String>();

    private int getCount()
    {
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(40);return m_menu.getCount();
    }

    private File getFile(int i)
    {
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(41);return new File(getValue(i));
    }

    private String getValue(int i)
    {
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(42);return m_menu.getValue(i);
    }

    private String getName(int i)
    {
        $qualityscroll_cover_jacov_probe_a1a548a4834e6acb(43);return getFile(i).getName();
    }
}
